### ISSUE TITLE
Add helm test setup script

### ISSUE THREAD

**Issue by afritzler** [onmetal/virtual-controlplane#16]
# Summary

Currently we are just using the `ct` command to do the testing. It is performed in the github action runner by setting up a temporary `kind` cluster. Ideally we need a testing script which also sets up all dependant helm charts like `cert-manager` and then applies our charts in the correct order.

**Comment by damyan** [comment]
I will be interested in a solution as well. I had some test action running (https://github.com/onmetal/kea-dhcp-pxe/blob/feature/add-github-actions/.github/workflows/helm-lint-test.yaml), but for whatever reason installing the kind cluster and trying to install the chart crashed the runner all the time...
